dist: bionic
language: ruby
rvm:
- 2.5.0

before_install:
- openssl aes-256-cbc -K $encrypted_86d18cc638e6_key -iv $encrypted_86d18cc638e6_iv
  -in deploy_key.enc -out /tmp/deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_key
- ssh-add /tmp/deploy_key



after_success:
[[ $TRAVIS_BRANCH = 'master' ]] && bundle exec cap staging deploy
