dist: bionic
language: ruby
rvm:
- 2.5.0
before_install:
- openssl aes-256-cbc -K $encrypted_a65247dffca0_key -iv $encrypted_a65247dffca0_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 0600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa

