language: ruby
rvm:
- 2.5.0
env:
  global:
    secure: Yn/qWSJ3s1x8tVM00t/KxGH+lSxMQzMJAAEsosdSydOn4+1wZKY8rLSyq6wYhma6FvxrjtAqBlE17fqZGRqBsJpW3E7wDf8lcnz1UYAbKqH1YmJFnOdDjZNCoROhqwDSNAN6JPDc0KDL9q610y4pg/zXEOyteY60q2gnVELGiqcUxl4W/6cFWrJNXsLGAtQvuQjg9hnDhUKILeXKOdbGug0zuJQCZhjhG6yCd16jtdeO/2hnRP7WjCymdh4IiLGIQ6GS4A809V4q7D9E7SkuatvpdEE3umIHerAAuX62IbIwfXTVp+5sxwnLSdDfhCt8i9VFm/klClFBCH4UE/EWhScuRJXFWwS70aNDqwEuA4cReFsMS0Z/4hZ/7RbjBaspZaNSnj9mNKeD1YGG6wljef2ubNajKwSPYAE0ExFayP/wkJKU8Nb9odmKouhZPkgu2JyOU/D5lHlRn+wiPSThaiF+yZ+Dcdgje5Q9QM7j+84lJDBhm/9bGaBdP8aRPHHjaZiXidW1NajBhfUP2MBSTtcmq+YwPSK/GqaEZ2F788U/A7rsK+8vXKhRB77o1yxSZjy3A6S3S6IM/FOZLvuUptGWxTzGseJZKKapgkePaTw8kWlv8oWmo18oACjZkmtppAk3DyQGjqk3iOHC2OQ6EBr1uPCxWPKbJgGLpVU+Sqk=
after_success:
  - "openssl aes-256-cbc -k $DEPLOY_KEY -in config/deploy_id_rsa_enc_travis -d -a -out config/deploy_id_rsa"
  - "bundle exec cap staging deploy"
